# =================================
# = Server
# =================================
server:
  port: 8080
  servlet:
    context-path: /v1

# =================================
# = Spring
# =================================
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://realmeet-db.cocimaocmxdt.sa-east-1.rds.amazonaws.com:3306/bluemeet?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
    username: admin
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    open-in-view: false

# =================================
# = Logging
# =================================
boot:
  logging:
    LogLevel:
      org.springframework: INFO
      org.flywaydb: INFO